#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# Roon Controller © Autolog 2019-2020
#

# plugin Zone Maps and Output Maps

ZONE_MAP_ALPHAS = list()
for minor_letter in ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']:
	for major_letter in [' ', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']:
		ZONE_MAP_ALPHAS.append('{}{}'.format(major_letter, minor_letter))

ZONE_MAP_ALPHAS.sort()

OUTPUT_MAP_NUMBERS = list()
for major_number in [' ', '1', '2', '3', '4', '5', '6', '7', '8', '9']:
	for minor_number in ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']:
		OUTPUT_MAP_NUMBERS.append('{}{}'.format(major_number, minor_number))

OUTPUT_MAP_NUMBERS.sort()

OUTPUT_MAP_NUMBERS.pop(0)  # Remove first entry = '0'

# Log Levels

K_LOG_LEVEL_NOT_SET = 0
K_LOG_LEVEL_DETAILED_DEBUGGING = 5
K_LOG_LEVEL_DEBUGGING = 10
K_LOG_LEVEL_INFO = 20
K_LOG_LEVEL_WARNING = 30
K_LOG_LEVEL_ERROR = 40
K_LOG_LEVEL_CRITICAL = 50

K_LOG_LEVEL_TRANSLATION = {}
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_NOT_SET] = "Not Set"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_DETAILED_DEBUGGING] = "Detailed debugging"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_DEBUGGING] = "Debugging"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_INFO] = "Info"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_WARNING] = "Warning"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_ERROR] = "Error"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_CRITICAL] = "Critical"


# plugin Constants
K_API_VERSION = 1
K_dynamic_Grouped_Zones_Rename = 32
K_AVAILABLE_OUTPUT_NUMBERS = 2
K_AVAILABLE_ZONE_ALPHAS = 3
K_CONFIG = 4
K_DEBUG = 5
K_DEVICES_TO_ROON_CONTROLLER_TABLE = 6
K_EXTENSION_INFO = 7
K_INDIGO_DEVICE_BEING_DELETED = 8
K_INDIGO_SERVER_ADDRESS = 9
K_MAP_OUTPUT = 10
K_MAP_ZONE = 11
K_OUTPUTS = 12
K_OUTPUT_ID_TO_DEV_ID = 13
K_PATH = 14
K_PLUGIN_DISPLAY_NAME = 15
K_PLUGIN_ID = 16
K_PLUGIN_INFO = 17
K_PLUGIN_PREFS_FOLDER = 18
K_PLUGIN_VERSION = 19
K_PRINT_OUTPUT = 20
K_PRINT_OUTPUTS_SUMMARY = 21
K_PRINT_ZONE = 22
K_PRINT_ZONES_SUMMARY = 23
K_ROON = 24
K_ROON_CORE_IP_ADDRESS = 25
K_ROON_DEVICE_FOLDER_ID = 26
K_ROON_DEVICE_FOLDER_NAME = 27
K_ZONES = 28
K_ZONE_UNIQUE_IDENTITY_KEY_TO_DEV_ID = 29
K_ZONE_UNIQUE_IDENTITY_KEY_TO_ZONE_ID = 30
K_AUTO_CREATE_DEVICES = 31
K_DYNAMIC_GROUPED_ZONES_RENAME = 33
K_ROON_VARIABLE_FOLDER_NAME = 34
K_ROON_VARIABLE_FOLDER_ID = 35
K_ZONE_UNIQUE_IDENTITY_KEY = 36
K_INDIGO_DEV_ID = 37
K_ROON_OUTPUT_ID = 38
K_TOKEN = 39
K_TOKEN_FILE = 40
K_API = 41
K_OUTPUTS_COUNT = 42
K_OUTPUTS = 43
K_DISPLAY_NAME = 44
K_OUTPUT_ID = 45
K_SOURCE_CONTROLS = 46
K_SOURCE_CONTROLS_COUNT = 47
K_VOLUME = 48
K_CAN_GROUP_WITH_OUTPUT_IDS = 49
K_STATUS = 50
K_CONTROL_KEY = 51
K_SUPPORTS_STANDBY = 52
K_ZONE_ID = 53
K_QUEUE_ITEMS_REMAINING = 54
K_QUEUE_TIME_REMAINING = 55
K_SETTINGS = 56
K_NOW_PLAYING = 57
K_AUTO_RADIO = 58
K_SHUFFLE = 59
K_LOOP = 60
K_ARTIST_IMAGE_KEYS = 61
K_ARTIST_IMAGE_KEYS_COUNT = 62
K_IMAGE_KEY = 63
K_ONE_LINE = 64
K_TWO_LINE = 65
K_THREE_LINE = 66
K_LINE_1 = 67
K_LINE_2 = 68
K_LINE_3 = 69
K_LENGTH = 70
K_SEEK_POSITION = 71
K_IS_PREVIOUS_ALLOWED = 72
K_IS_PAUSE_ALLOWED = 73
K_IS_SEEK_ALLOWED = 74
K_STATE = 75
K_IS_PLAY_ALLOWED = 76
K_IS_NEXT_ALLOWED = 77
K_DEVICE_STARTED = 78

K_VOLUME_HARD_LIMIT_MIN = 79
K_VOLUME_MIN = 80
K_VOLUME_IS_MUTED = 81
K_VOLUME_MAX = 82
K_VOLUME_VALUE = 83
K_VOLUME_STEP = 84
K_VOLUME_HARD_LIMIT_MAX = 85
K_VOLUME_SOFT_LIMIT = 86
K_VOLUME_TYPE = 87

K_CAN_GROUP_WITH_OUTPUT_IDS_COUNT = 88
K_REMAINING = 89
K_DISPLAY_TRACK_PLAYING = 90

K_TRANSLATION = dict()








# Image Types
ARTIST = 0
ALBUM = 1

# QUEUE Priorities
QUEUE_PRIORITY_STOP_THREAD    = 0
QUEUE_PRIORITY_INIT_DISCOVERY = 50
QUEUE_PRIORITY_WAVEFORM       = 100
QUEUE_PRIORITY_COMMAND_HIGH   = 200
QUEUE_PRIORITY_COMMAND_MEDIUM = 300
QUEUE_PRIORITY_STATUS_HIGH    = 400
QUEUE_PRIORITY_STATUS_MEDIUM  = 500
QUEUE_PRIORITY_DISCOVERY      = 600
QUEUE_PRIORITY_POLLING        = 700
QUEUE_PRIORITY_LOW            = 800
